#!/usr/bin/env node
'use strict';
// Writes web/checklist.js: the checklist data the landing page on andryta.com
// uses to show the 16 sections and their items. Run after editing
// src/checklist.js, then upload web/checklist.js again.
const fs = require('fs');
const path = require('path');
const cl = require('../src/checklist');
const out = path.join(__dirname, '..', 'web', 'checklist.js');
const data = { SECTIONS: cl.SECTIONS, ITEMS: cl.ITEMS.map(i => cl.itemFor(i.id)) };
fs.writeFileSync(out, '// Generated by scripts/build-web.js from src/checklist.js. Do not edit.\nwindow.CHECKLIST=' + JSON.stringify(data) + ';\n');
console.log(`wrote ${path.relative(process.cwd(), out)}: ${data.SECTIONS.length} sections, ${data.ITEMS.length} items, ${(fs.statSync(out).size / 1024).toFixed(0)} KB`);
