'use strict';
// The A11Y Project checklist (https://www.a11yproject.com/checklist/), as data.
//
// Every rule in src/rules maps to exactly one item here, so a finding can
// always say which checklist entry it fails, which WCAG criterion that entry
// cites, what the criterion is about, and where to read more. The wording of
// the items and their anchors follows the checklist so the share links land
// on the right entry.

const WCAG_BASE = 'https://www.w3.org/WAI/WCAG22/Understanding/';
const CHECKLIST_BASE = 'https://www.a11yproject.com/checklist/';

// Success criteria the checklist cites: name, level, and the slug of the
// W3C "Understanding" page.
const WCAG = {
  '1.1.1': { name: 'Non-text Content', level: 'A', slug: 'non-text-content' },
  '1.2.2': { name: 'Captions (Prerecorded)', level: 'A', slug: 'captions-prerecorded' },
  '1.3.1': { name: 'Info and Relationships', level: 'A', slug: 'info-and-relationships' },
  '1.3.2': { name: 'Meaningful Sequence', level: 'A', slug: 'meaningful-sequence' },
  '1.3.3': { name: 'Sensory Characteristics', level: 'A', slug: 'sensory-characteristics' },
  '1.3.4': { name: 'Orientation', level: 'AA', slug: 'orientation' },
  '1.3.5': { name: 'Identify Input Purpose', level: 'AA', slug: 'identify-input-purpose' },
  '1.4.1': { name: 'Use of Color', level: 'A', slug: 'use-of-color' },
  '1.4.2': { name: 'Audio Control', level: 'A', slug: 'audio-control' },
  '1.4.3': { name: 'Contrast (Minimum)', level: 'AA', slug: 'contrast-minimum' },
  '1.4.4': { name: 'Resize Text', level: 'AA', slug: 'resize-text' },
  '1.4.8': { name: 'Visual Presentation', level: 'AAA', slug: 'visual-presentation' },
  '1.4.10': { name: 'Reflow', level: 'AA', slug: 'reflow' },
  '1.4.11': { name: 'Non-text Contrast', level: 'AA', slug: 'non-text-contrast' },
  '2.1.1': { name: 'Keyboard', level: 'A', slug: 'keyboard' },
  '2.2.1': { name: 'Timing Adjustable', level: 'A', slug: 'timing-adjustable' },
  '2.2.2': { name: 'Pause, Stop, Hide', level: 'A', slug: 'pause-stop-hide' },
  '2.3.1': { name: 'Three Flashes or Below Threshold', level: 'A', slug: 'three-flashes-or-below-threshold' },
  '2.3.3': { name: 'Animation from Interactions', level: 'AAA', slug: 'animation-from-interactions' },
  '2.4.1': { name: 'Bypass Blocks', level: 'A', slug: 'bypass-blocks' },
  '2.4.2': { name: 'Page Titled', level: 'A', slug: 'page-titled' },
  '2.4.3': { name: 'Focus Order', level: 'A', slug: 'focus-order' },
  '2.4.4': { name: 'Link Purpose (In Context)', level: 'A', slug: 'link-purpose-in-context' },
  '2.4.6': { name: 'Headings and Labels', level: 'AA', slug: 'headings-and-labels' },
  '2.4.7': { name: 'Focus Visible', level: 'AA', slug: 'focus-visible' },
  '2.5.5': { name: 'Target Size (Enhanced)', level: 'AAA', slug: 'target-size-enhanced' },
  '2.5.8': { name: 'Target Size (Minimum)', level: 'AA', slug: 'target-size-minimum' },
  '3.1.1': { name: 'Language of Page', level: 'A', slug: 'language-of-page' },
  '3.1.5': { name: 'Reading Level', level: 'AAA', slug: 'reading-level' },
  '3.2.2': { name: 'On Input', level: 'A', slug: 'on-input' },
  '3.3.1': { name: 'Error Identification', level: 'A', slug: 'error-identification' },
  '3.3.2': { name: 'Labels or Instructions', level: 'A', slug: 'labels-or-instructions' },
  '4.1.1': { name: 'Parsing', level: 'A', slug: 'parsing',
             note: 'Removed in WCAG 2.2 (always satisfied); the checklist still cites it. Duplicate ids and broken nesting are reported under 4.1.2 and 1.3.1 in 2.2.' },
  '4.1.2': { name: 'Name, Role, Value', level: 'A', slug: 'name-role-value' },
  'G201': { name: 'Giving users advanced warning when opening a new window', level: 'Technique',
            url: 'https://www.w3.org/WAI/WCAG22/Techniques/general/G201' }
};

const SECTIONS = [
  { id: 'content', title: 'Content', blurb: 'Content is the most important part of your site.' },
  { id: 'global-code', title: 'Global code', blurb: 'Global code is code that affects your entire website or web app.' },
  { id: 'keyboard', title: 'Keyboard', blurb: 'It is important that your interface and content can be operated, and navigated by use of a keyboard. Some people cannot use a mouse, or may be using other assistive technologies that may not allow for hovering or precise clicking.' },
  { id: 'images', title: 'Images', blurb: 'Images are a very common part of most websites. Help make sure they can be enjoyed by all.' },
  { id: 'headings', title: 'Headings', blurb: 'Heading elements (h1, h2, h3, etc.) help break up the content of the page into related "chunks" of information. They are incredibly important for helping people who use assistive technology to understand the meaning of a page or view.' },
  { id: 'lists', title: 'Lists', blurb: 'Lists elements let people know a collection of items are related and if they are sequential, and how many items are present in the list grouping.' },
  { id: 'controls', title: 'Controls', blurb: 'Controls are interactive elements such as links and buttons that let a person navigate to a destination or perform an action.' },
  { id: 'tables', title: 'Tables', blurb: 'Tables are a structured set of data that help people understand the relationships between different types of information.' },
  { id: 'forms', title: 'Forms', blurb: 'Forms allow people to enter information into a site for processing and manipulation. This includes things like sending messages and placing orders.' },
  { id: 'media', title: 'Media', blurb: 'Media includes content such as pre-recorded and live audio and video.' },
  { id: 'video', title: 'Video', blurb: 'Video-specific checks.' },
  { id: 'audio', title: 'Audio', blurb: 'Audio-specific checks.' },
  { id: 'appearance', title: 'Appearance', blurb: 'How your website app content looks in any given situation.' },
  { id: 'animation', title: 'Animation', blurb: 'Animation is movement in the page: transitions, autoplaying video, and effects that respond to scrolling or pointer position.' },
  { id: 'color-contrast', title: 'Color contrast', blurb: 'Color contrast is how legible colors are when placed next to, and on top of each other.' },
  { id: 'mobile-and-touch', title: 'Mobile and touch', blurb: 'What was once only a consideration for phones and tablets is now often the primary way people use the web.' }
];

// automated: 'yes' the scanner decides; 'partial' it finds what it can and a
// person finishes; 'no' a person must check, the scanner only points at the
// relevant elements.
const ITEMS = [
  // ---------------------------------------------------------------- Content
  { id: 'plain-language', section: 'content', wcag: '3.1.5',
    title: 'Use plain language and avoid figures of speech, idioms, and complicated metaphors.',
    description: 'Write content at an 8th grade reading level.',
    anchor: 'use-plain-language-and-avoid-figures-of-speech-idioms-and-complicated-metaphors',
    automated: 'partial',
    about: 'People with cognitive or learning disabilities, people reading in a second language, and anyone in a hurry understand simple sentences and common words. WCAG 3.1.5 asks that text harder than lower secondary education level has a simpler version available.',
    measures: 'Reads the visible body text and estimates its Flesch-Kincaid grade level. A page well above grade 9 is flagged for review; idioms and metaphors still need a person.',
    fix: 'Shorten sentences, prefer common words, and explain any term a newcomer would not know. Aim at an 8th grade reading level.' },
  { id: 'unique-descriptive-controls', section: 'content', wcag: '1.3.1',
    title: 'Make sure that button, a, and label element content is unique and descriptive.',
    description: 'Terms like "click here" and "read more" do not provide any context. Some people navigate using a list of all buttons or links on a page or view. When using this mode, the terms indicate what will happen if navigated to or activated.',
    anchor: 'make-sure-that-button-a-and-label-element-content-is-unique-and-descriptive',
    automated: 'yes',
    about: 'Screen reader users often pull up a list of every link or button on the page. Out of context, "Read more" said six times tells them nothing. Each control name should say where it goes or what it does.',
    measures: 'Finds links and buttons whose name is a generic phrase, and links that share the same text but point at different addresses.',
    fix: 'Rewrite the text so it names the destination or action: "Read the 2026 annual report" rather than "Read more". Where the visible text must stay short, add the detail with aria-label or visually hidden text.' },
  { id: 'text-alignment', section: 'content', wcag: '1.4.8',
    title: 'Use left-aligned text for left-to-right (LTR) languages, and right-aligned text for right-to-left (RTL) languages.',
    description: 'Centered-aligned or justified text is difficult to read.',
    anchor: 'use-left-aligned-text-for-left-to-right-ltr-languages-and-right-aligned-text-for-right-to-left-rtl-languages',
    automated: 'yes',
    about: 'Justified text opens uneven gaps between words that people with dyslexia find hard to track; centered paragraphs give the eye no fixed edge to return to on each line. Short headings are fine; running text is the problem.',
    measures: 'Finds paragraphs of running text (more than about 150 characters) that are justified or centered.',
    fix: 'Set text-align to start (left for LTR, right for RTL) on body copy. Keep centring for short headings and captions only.' },

  // ------------------------------------------------------------ Global code
  { id: 'validate-html', section: 'global-code', wcag: '4.1.1',
    title: 'Validate your HTML.',
    description: 'Valid HTML helps to provide a consistent, expected experience across all browsers and assistive technology.',
    anchor: 'validate-your-html',
    automated: 'partial',
    about: 'Browsers repair broken markup silently, but each repairs it differently, and assistive technology reads the repaired tree. Duplicate ids break every label, description and control that refers to them; interactive elements nested inside each other confuse both.',
    measures: 'Finds duplicate id values and interactive elements nested inside other interactive elements (a link inside a button, a button inside a link). Run the W3C validator for the full picture.',
    fix: 'Make every id unique on the page. Never nest a button or link inside another button or link. Validate at https://validator.w3.org/.' },
  { id: 'lang-attribute', section: 'global-code', wcag: '3.1.1',
    title: 'Use a lang attribute on the html element.',
    description: 'This helps assistive technology such as screen readers to pronounce the content correctly.',
    anchor: 'use-a-lang-attribute-on-the-html-element',
    automated: 'yes',
    about: 'A screen reader picks its pronunciation rules from the page language. Without it, English text can be read with French rules and become unintelligible. The attribute also drives hyphenation, quotation marks and translation tools.',
    measures: 'Checks that the html element has a lang attribute with a well-formed language tag.',
    fix: 'Add lang="en" (or the page\'s real language) to the html element in the template.' },
  { id: 'unique-title', section: 'global-code', wcag: '2.4.2',
    title: 'Provide a unique title for each page or view.',
    description: 'The title element, contained in the document\'s head element, is often the first piece of information announced by assistive technology. This helps tell people what page or view they are going to start interacting with.',
    anchor: 'provide-a-unique-title-for-each-page-or-view',
    automated: 'yes',
    about: 'The title is what a screen reader announces first, what appears in browser tabs and history, and what a search engine shows. Two pages with the same title cannot be told apart.',
    measures: 'Checks that the page has a non-empty title and, across the pages in this run, that no two pages share one.',
    fix: 'Give every page a title of the form "Page name – Site name". Set it from the page content, not from a fixed template string.' },
  { id: 'viewport-zoom', section: 'global-code', wcag: '1.4.4',
    title: 'Ensure that viewport zoom is not disabled.',
    description: 'Some people need to increase the size of text to a point where they can read it. Do not stop them from doing this, even for web apps with a native app-like experience.',
    anchor: 'ensure-that-viewport-zoom-is-not-disabled',
    automated: 'yes',
    about: 'On a phone, pinch zoom is the only way many people with low vision can read at all. user-scalable=no and a maximum-scale below 2 switch it off.',
    measures: 'Reads the viewport meta tag for user-scalable=no or a maximum-scale under 2.',
    fix: 'Use <meta name="viewport" content="width=device-width, initial-scale=1"> and nothing that limits scaling.' },
  { id: 'landmarks', section: 'global-code', wcag: '4.1.2',
    title: 'Use landmark elements to indicate important content regions.',
    description: 'Landmark regions help communicate the layout and important areas of a page or view, and can allow quick access to these regions. For example, use the nav element to wrap a site\'s navigation, and the main element to contain the primary content of a page.',
    anchor: 'use-landmark-elements-to-indicate-important-content-regions',
    automated: 'yes',
    about: 'Screen readers offer a list of landmarks (banner, navigation, main, contentinfo) as a way to jump straight to a region. A page without a main landmark forces people to read through everything above it.',
    measures: 'Checks for a main landmark, for a navigation landmark when the page has a menu of links, and for content left outside any landmark.',
    fix: 'Wrap the page body in <main>, the menu in <nav>, the header in <header> and the footer in <footer>. Use one main per page.' },
  { id: 'linear-content-flow', section: 'global-code', wcag: '2.4.3',
    title: 'Ensure a linear content flow.',
    description: 'Remove tabindex attribute values that aren\'t either 0 or -1. Elements that are inherently focusable, such as links or button elements, do not require a tabindex. Elements that are not inherently focusable should not have a tabindex applied to them outside of very specific use cases.',
    anchor: 'ensure-a-linear-content-flow',
    automated: 'yes',
    about: 'A positive tabindex pulls an element to the front of the tab order regardless of where it sits on the page, so keyboard focus jumps around in an order nobody can predict.',
    measures: 'Finds elements with a tabindex greater than 0, and non-interactive elements given tabindex="0".',
    fix: 'Remove positive tabindex values and let the document order decide. Use tabindex="0" only on custom controls, and tabindex="-1" for programmatic focus targets.' },
  { id: 'no-autofocus', section: 'global-code', wcag: '2.4.3',
    title: 'Avoid using the autofocus attribute.',
    description: 'People who are blind or who have low vision may be disoriented when focus is moved without their permission. Additionally, autofocus can be problematic for people with motor control disabilities, as it may create extra work for them to navigate out from the autofocused area and to other locations on the page/view.',
    anchor: 'avoid-using-the-autofocus-attribute',
    automated: 'yes',
    about: 'Moving focus on page load skips the heading and the context that comes before the field, so a screen reader user lands in a text box without knowing what page they are on.',
    measures: 'Finds elements carrying the autofocus attribute.',
    fix: 'Remove autofocus. Let people reach the field in reading order.' },
  { id: 'session-timeouts', section: 'global-code', wcag: '2.2.1',
    title: 'Allow extending session timeouts.',
    description: 'If you cannot remove session timeouts altogether, then let the person using your site easily turn off, adjust, or extend their session well before it ends.',
    anchor: 'allow-extending-session-timeouts',
    automated: 'partial',
    about: 'People who read slowly, use a screen reader or type with one hand need more time. A page that refreshes or redirects itself, or a session that ends without warning, takes their work away.',
    measures: 'Finds meta refresh redirects and timed reloads. Session behavior behind a login still needs a person.',
    fix: 'Remove meta refresh. Warn before a session ends and offer a one-click extension of at least 20 seconds notice, or make the limit at least 20 hours.' },
  { id: 'title-tooltips', section: 'global-code', wcag: '4.1.2',
    title: 'Remove title attribute tooltips.',
    description: 'The title attribute has numerous issues, and should not be used if the information provided is important for all people to access. An acceptable use for the title attribute would be labeling an iframe element to indicate what content it contains.',
    anchor: 'remove-title-attribute-tooltips',
    automated: 'yes',
    about: 'Title tooltips appear only on mouse hover: never on touch, never for keyboard users, and inconsistently for screen readers. Anything that only exists in a title attribute is invisible to most of the people who would need it.',
    measures: 'Finds controls whose only name comes from a title attribute, and other non-iframe elements using title for information.',
    fix: 'Move the text into visible content, a label, or aria-label. Keep title only on iframe elements.' },

  // --------------------------------------------------------------- Keyboard
  { id: 'visible-focus', section: 'keyboard', wcag: '2.4.7',
    title: 'Make sure there is a visible focus style for interactive elements that are navigated to via keyboard input.',
    description: 'Can a person navigating with a keyboard, switch, voice control, or screen reader see where they currently are on the page?',
    anchor: 'make-sure-there-is-a-visible-focus-style-for-interactive-elements-that-are-navigated-to-via-keyboard-input',
    automated: 'yes',
    about: 'Someone tabbing through a page has no cursor. The focus ring is the only thing that tells them which control will act when they press Enter. Removing it with outline:none and adding nothing back makes the page unusable without a mouse.',
    measures: 'Presses Tab through the page and reads what actually changed on screen at each stop: outline, box-shadow, border or pseudo-element on the control or an ancestor.',
    fix: 'Never remove the focus ring without replacing it. A 2px solid outline with a 2px offset, in a color that reaches 3:1 against the surroundings, is enough. Use :focus-visible so mouse users are not affected.' },
  { id: 'focus-order-visual', section: 'keyboard', wcag: '1.3.2',
    title: 'Check to see that keyboard focus order matches the visual layout.',
    description: 'Can a person navigating with a keyboard or screen reader move around the page in a predictable way?',
    anchor: 'check-to-see-that-keyboard-focus-order-matches-the-visual-layout',
    automated: 'partial',
    about: 'Focus should travel the way the eye does: top to bottom, start to end. CSS that reorders boxes (flex order, grid placement, floats) leaves the tab order following the source, so focus visibly jumps backwards.',
    measures: 'Records the position of each tab stop and flags jumps where focus moves far back up the page after having moved down. Small reversals inside a row are ignored.',
    fix: 'Order the source the way the layout reads. Avoid the CSS order property on interactive content, or reorder the markup to match.' },
  { id: 'invisible-focusable', section: 'keyboard', wcag: '2.4.3',
    title: 'Remove invisible focusable elements.',
    description: 'Remove the ability to focus on elements that are not presently meant to be discoverable. This includes things like inactive drop down menus, off screen navigations, or modals.',
    anchor: 'remove-invisible-focusable-elements',
    automated: 'yes',
    about: 'A closed menu that is only moved off screen still takes Tab presses. A keyboard user sees focus disappear for several stops, and a screen reader user is offered links inside content the page says is hidden.',
    measures: 'Presses Tab through the page and finds stops that have no size, sit off screen, are transparent, or are inside an aria-hidden region.',
    fix: 'Hide inactive content with display:none, the hidden attribute or inert, so it leaves the tab order. If it must stay in the DOM, set tabindex="-1" on its controls.' },

  // ----------------------------------------------------------------- Images
  { id: 'img-alt', section: 'images', wcag: '1.1.1',
    title: 'Make sure that all img elements have an alt attribute.',
    description: 'alt attributes (alternative text) give a description of an image for people who may not be able to view them. When an alt attribute isn\'t present on an image, a screen reader may announce the image\'s file name and path instead. This fails to communicate the image\'s content.',
    anchor: 'make-sure-that-all-img-elements-have-an-alt-attribute',
    automated: 'yes',
    about: 'Without alt a screen reader reads out "IMG_2041.jpg" or the whole URL. With a good alt it reads what the image shows or does. This is the single most common accessibility failure on the web.',
    measures: 'Finds img elements with no alt attribute at all.',
    fix: 'Add alt text saying what the image conveys in this context. If the image is purely decorative, add alt="" so it is skipped.' },
  { id: 'decorative-null-alt', section: 'images', wcag: '1.1.1',
    title: 'Make sure that decorative images use null alt (empty) attribute values.',
    description: 'Null alt attributes are also sometimes known as empty alt attributes. They are made by including no information between the opening and closing quotes of an alt attribute. Decorative images do not communicate information that is required to understand the website\'s overall meaning. Historically they were used for flourishes and spacer gif images, but tend to be less relevant for modern websites and web apps.',
    anchor: 'make-sure-that-decorative-images-use-null-alt-empty-attribute-values',
    automated: 'partial',
    about: 'An alt like "image", "spacer" or "photo.png" is worse than none: it is announced and says nothing. Decorative images need alt="" so they disappear from the reading order.',
    measures: 'Finds alt text that is a filename, a placeholder word (image, photo, picture, icon, graphic, spacer, logo on its own), or that repeats the adjacent link text.',
    fix: 'Set alt="" on decoration. Where the image carries meaning, describe the meaning rather than naming the file.' },
  { id: 'complex-images', section: 'images', wcag: '1.1.1',
    title: 'Provide a text alternative for complex images such as charts, graphs, and maps.',
    description: 'Is there a plain text which lists points on the map or sections of a flowchart? Describe all visible information. This includes graph axes, data points and labels, and the overall point the graphic is communicating.',
    anchor: 'provide-a-text-alternative-for-complex-images-such-as-charts-graphs-and-maps',
    automated: 'partial',
    about: 'A one-line alt cannot carry a chart. Complex images need a longer description nearby: a data table, a paragraph, or a linked page.',
    measures: 'Finds large images, canvases and SVG graphics with no long description (aria-describedby, figcaption, or a details element). Whether the description is adequate needs a person.',
    fix: 'Add a figcaption or aria-describedby pointing at text that states the axes, the values and the conclusion. For canvas and SVG charts, add role="img" with a name and a description.' },
  { id: 'images-of-text', section: 'images', wcag: '1.1.1',
    title: 'For images containing text, make sure the alt description includes the image\'s text.',
    description: 'For example, the FedEx logo should have an alt value of "FedEx."',
    anchor: 'for-images-containing-text-make-sure-the-alt-description-includes-the-images-text',
    automated: 'no',
    about: 'Text in a picture is invisible to a screen reader, to search, and to translation. The alt must carry the words.',
    measures: 'Lists images that look like logos or banners (inside links, in the header, wide and short) so a person can check their alt text against the picture.',
    fix: 'Put the visible words into the alt attribute. Better still, render text as text.' },

  // --------------------------------------------------------------- Headings
  { id: 'headings-introduce-content', section: 'headings', wcag: '2.4.6',
    title: 'Use heading elements to introduce content.',
    description: 'Heading elements construct a document outline, and should not be used for purely visual design.',
    anchor: 'use-heading-elements-to-introduce-content',
    automated: 'partial',
    about: 'Screen reader users navigate by heading: a list of h1 to h6 is their table of contents. Text that merely looks like a heading (big and bold) does not appear in that list; an empty heading appears with nothing to say.',
    measures: 'Finds pages with no headings, empty headings, and short blocks of large bold text that are not marked up as headings.',
    fix: 'Mark every section title as a heading element at the right level. Style it with CSS. Remove empty headings.' },
  { id: 'one-h1', section: 'headings', wcag: '2.4.6',
    title: 'Use only one h1 element per page or view.',
    description: 'The h1 element should be used to communicate the high-level purpose of the page or view. Do not use the h1 element for a heading that does not change between pages or views (for example, the site\'s name).',
    anchor: 'use-only-one-h1-element-per-page-or-view',
    automated: 'yes',
    about: 'The h1 answers "what is this page". None means the outline has no top; several mean it has several tops and none of them is the page.',
    measures: 'Counts h1 elements (and role="heading" aria-level="1") on the page.',
    fix: 'Use exactly one h1 carrying the page title. Demote the others to the level their position implies.' },
  { id: 'heading-sequence', section: 'headings', wcag: '2.4.6',
    title: 'Heading elements should be written in a logical sequence.',
    description: 'The order of heading elements should descend, based on the "depth" of the content. For example, a h4 element should not appear on a page before the first h3 element declaration.',
    anchor: 'heading-elements-should-be-written-in-a-logical-sequence',
    automated: 'yes',
    about: 'The outline only works if levels nest: a section (h2) contains subsections (h3). A page that starts at h3, or puts an h4 before any h3, has an outline nobody can follow.',
    measures: 'Checks that the first heading is an h1 and that no level appears before its parent level has.',
    fix: 'Start at h1 and open each deeper level only inside the one above it.' },
  { id: 'no-skipped-levels', section: 'headings', wcag: '2.4.6',
    title: 'Don\'t skip heading levels.',
    description: 'For example, don\'t jump from a h2 to a h4, skipping a h3 element. If heading levels are being skipped for a specific visual treatment, use CSS classes instead.',
    anchor: 'dont-skip-heading-levels',
    automated: 'yes',
    about: 'A jump from h2 to h4 suggests a missing h3 section. People navigating by level land on nothing.',
    measures: 'Finds any heading more than one level deeper than the heading before it.',
    fix: 'Choose heading levels by position in the outline, not by size. Style with a CSS class instead of skipping a level.' },

  // ------------------------------------------------------------------ Lists
  { id: 'list-elements', section: 'lists', wcag: '1.3.1',
    title: 'Use list elements (ol, ul, and dl elements) for list content.',
    description: 'This may include sections of related content, items visually displayed in a grid-like layout, or sibling a elements.',
    anchor: 'use-list-elements-ol-ul-and-dl-elements-for-list-content',
    automated: 'partial',
    about: 'A real list tells a screen reader "list, five items" and lets the person skip it or step through it. Five links in a div, or lines that begin with a typed bullet, do not.',
    measures: 'Finds groups of three or more sibling links outside any list, navigation without a list, fake bullets typed as text, and list items placed outside a list.',
    fix: 'Wrap related items in ul or ol with an li each; use dl for name–value pairs. Style the list with CSS.' },

  // --------------------------------------------------------------- Controls
  { id: 'a-for-links', section: 'controls', wcag: '1.3.1',
    title: 'Use the a element for links.',
    description: 'Links should always have a href attribute, even in Single Page Applications (SPAs). Without a href attribute, the link will not be properly exposed to assistive technology. An example of this would be a link that uses an onclick event, in place of a href attribute.',
    anchor: 'use-the-a-element-for-links',
    automated: 'yes',
    about: 'An a element without href is not a link to the browser: it cannot be tabbed to, has no role, and is skipped by the screen reader\'s link list. Clickable divs and spans have the same problem.',
    measures: 'Finds a elements without href, elements with role="link" that are not real links, and non-interactive elements carrying click handlers.',
    fix: 'Use <a href="…"> for navigation, with a real destination. In a SPA, still set href and intercept the click.' },
  { id: 'links-recognizable', section: 'controls', wcag: '1.4.1',
    title: 'Ensure that links are recognizable as links.',
    description: 'Color alone is not sufficient to indicate the presence of a link. Underlines are a popular and commonly-understood way to communicate the presence of link content.',
    anchor: 'ensure-that-links-are-recognizable-as-links',
    automated: 'yes',
    about: 'One person in twelve has some form of color blindness. A blue word in a black sentence, with no underline, is just a word to them.',
    measures: 'Finds links inside running text that have no underline or border and whose color differs from the surrounding text by less than 3:1.',
    fix: 'Underline links in body text, or give them a second cue besides color (weight, icon, border) and at least 3:1 color difference from the surrounding text.' },
  { id: 'controls-focus-states', section: 'controls', wcag: '2.4.7',
    title: 'Ensure that controls have :focus states.',
    description: 'Visible focus styles help people determine which interactive element has keyboard focus. This lets them know that they can perform actions like activating a button or navigating to a link\'s destination.',
    anchor: 'ensure-that-controls-have-focus-states',
    automated: 'yes',
    about: 'Beyond existing, the focus indicator has to be seen. A gray ring on a gray card, or a ring that only differs from the button by a shade, disappears for people with low vision.',
    measures: 'For each tab stop that does have an indicator, measures its contrast against what sits behind it (3:1 required by 1.4.11) and notes controls relying on the browser default.',
    fix: 'Recolor the focus ring so it reaches 3:1 against the surrounding surface. A two-tone ring (light inner, dark outer) survives light and dark backgrounds.' },
  { id: 'button-for-buttons', section: 'controls', wcag: '1.3.1',
    title: 'Use the button element for buttons.',
    description: 'Buttons are used to submit data or perform an on-screen action which does not shift keyboard focus. You can add type="button" to a button element to prevent the browser from attempting to submit form information when activated.',
    anchor: 'use-the-button-element-for-buttons',
    automated: 'yes',
    about: 'A div with a click handler has no role, no name, no keyboard behavior and no focus. A link with href="#" says "link" and scrolls to the top. Only button gives you all of it for free.',
    measures: 'Finds links with href="#" or javascript: used as buttons, elements with role="button" that are not buttons, and clickable div/span elements.',
    fix: 'Use <button type="button"> for actions. Reserve links for navigation.' },
  { id: 'skip-link', section: 'controls', wcag: '2.4.1',
    title: 'Provide a skip link and make sure that it is visible when focused.',
    description: 'A skip link can be used to provide quick access to the main content of a page or view. This allows a person to easily bypass globally repeated content such as a website\'s primary navigation, or persistent search widget.',
    anchor: 'provide-a-skip-link-and-make-sure-that-it-is-visible-when-focused',
    automated: 'yes',
    about: 'Without a skip link a keyboard user tabs through every header link on every page before reaching the content. The link may be hidden until focused, but on focus it must appear.',
    measures: 'Looks for an in-page link before the main content, focuses it, and checks it is visible and that its target exists.',
    fix: 'Add <a href="#main">Skip to content</a> as the first focusable element, positioned off screen until :focus, pointing at the main landmark.' },
  { id: 'new-window-links', section: 'controls', wcag: 'G201',
    title: 'Identify links that open in a new tab or window.',
    description: 'Ideally, avoid links that open in a new tab or window. If a link does, ensure the link\'s behavior will be communicated in a way that is apparent to all users. This will help people understand what will happen before activating the link.',
    anchor: 'identify-links-that-open-in-a-new-tab-or-window',
    automated: 'yes',
    about: 'A new tab breaks the Back button and moves a screen reader user somewhere without warning. If it has to happen, say so in the link.',
    measures: 'Finds links with target="_blank" whose name does not say the link opens in a new window or tab.',
    fix: 'Remove target="_blank" where you can. Otherwise add "(opens in a new tab)" to the link text or aria-label, and an icon with matching alt.' },

  // ----------------------------------------------------------------- Tables
  { id: 'table-for-data', section: 'tables', wcag: '1.3.1',
    title: 'Use the table element to describe tabular data.',
    description: 'Do you need to display data in rows and columns? Use the table element.',
    anchor: 'use-the-table-element-to-describe-tabular-data',
    automated: 'partial',
    about: 'A screen reader can move through a real table cell by cell and announce the header for each. A grid built from divs is read as a flat list of numbers with no relationships.',
    measures: 'Finds tables used for page layout (no headers, nested block content) and grids built from repeated rows of divs. Whether the content is really tabular needs a person.',
    fix: 'Use table, thead, th and td for data. Use CSS grid or flexbox, not table, for layout.' },
  { id: 'th-scope', section: 'tables', wcag: '4.1.1',
    title: 'Use the th element for table headers (with appropriate scope attributes).',
    description: 'Depending on how complex your table is, you may also consider using scope="col" for column headers, and scope="row" for row headers. Many different kinds of assistive technology still use the scope attribute to help them understand and describe the structure of a table.',
    anchor: 'use-the-th-element-for-table-headers-with-appropriate-scope-attributes',
    automated: 'yes',
    about: 'Headers marked as th are announced with each cell: "Price, 42". Headers styled as bold td are not.',
    measures: 'Finds data tables with no th elements, and tables with both row and column headers where the th elements have no scope.',
    fix: 'Mark header cells as th. Add scope="col" or scope="row". For irregular tables, use headers/id.' },
  { id: 'table-caption', section: 'tables', wcag: '2.4.6',
    title: 'Use the caption element to provide a title for the table.',
    description: 'The table\'s caption should describe what kind of information the table contains.',
    anchor: 'use-the-caption-element-to-provide-a-title-for-the-table',
    automated: 'yes',
    about: 'The caption is announced when a screen reader reaches the table, so the person knows what they are about to read before the first cell.',
    measures: 'Finds data tables with no caption, aria-label or aria-labelledby.',
    fix: 'Add a caption as the first child of the table, or aria-labelledby pointing at the heading above it.' },

  // ------------------------------------------------------------------ Forms
  { id: 'input-labels', section: 'forms', wcag: '3.2.2',
    title: 'All inputs in a form are associated with a corresponding label element.',
    description: 'Use a for/id pairing to guarantee the highest level of browser/assistive technology support.',
    anchor: 'all-inputs-in-a-form-are-associated-with-a-corresponding-label-element',
    automated: 'yes',
    about: 'A field with no label is announced as "edit text". Placeholder text is not a label: it vanishes when typing begins and is often too pale to read. A label also enlarges the click target.',
    measures: 'Finds inputs, selects and textareas with no label element, aria-label or aria-labelledby.',
    fix: 'Add <label for="id"> for every field, or wrap the field in its label. Keep placeholders as hints only.' },
  { id: 'fieldset-legend', section: 'forms', wcag: '1.3.1',
    title: 'Use fieldset and legend elements where appropriate.',
    description: 'Does your form contain multiple sections of related inputs? Use fieldset to group them, and legend to provide a label for what this section is for.',
    anchor: 'use-fieldset-and-legend-elements-where-appropriate',
    automated: 'yes',
    about: 'A radio button labeled "Yes" means nothing without the question. The legend of the fieldset supplies it to a screen reader.',
    measures: 'Finds groups of radio buttons or checkboxes sharing a name that are not inside a fieldset with a legend (or a role="group" with a name).',
    fix: 'Wrap each group in fieldset and put the question in legend.' },
  { id: 'autocomplete', section: 'forms', wcag: '1.3.5',
    title: 'Inputs use autocomplete where appropriate.',
    description: 'Providing a mechanism to help people more quickly and easily fill out form inputs that request information about them helps them save time and reduces the chance of errors.',
    anchor: 'inputs-use-autocomplete-where-appropriate',
    automated: 'yes',
    about: 'The autocomplete token lets the browser fill name, email, address and phone for the person, and lets assistive technology add its own icon or label to the field. People with motor or memory impairments depend on it.',
    measures: 'Finds fields whose type, name or id suggests personal data (email, telephone, name, address, postcode, country) that carry no autocomplete attribute.',
    fix: 'Add the matching token: autocomplete="email", "tel", "name", "street-address", "postal-code", "country-name", and so on.' },
  { id: 'errors-listed-above-form', section: 'forms', wcag: '3.3.1',
    title: 'Make sure that form input errors are displayed in list above the form after submission.',
    description: 'This provides a way for assistive technology users to quickly have a high-level understanding of what issues are present in the form. This is especially important for larger forms with many inputs. Make sure that each reported error also has a link to the corresponding input.',
    anchor: 'make-sure-that-form-input-errors-are-displayed-in-list-above-the-form-after-submission',
    automated: 'no',
    about: 'After a failed submission a sighted person scans for red text. A screen reader user needs a summary at the top that names each problem and links to the field.',
    measures: 'Not automated: the scanner does not submit forms. Pages with forms are listed for a manual check.',
    fix: 'On submission failure, move focus to a summary list above the form; each entry links to the field.' },
  { id: 'error-messaging-associated', section: 'forms', wcag: '3.3.1',
    title: 'Associate input error messaging with the input it corresponds to.',
    description: 'Techniques such as using aria-describedby allow people who use assistive technology to more easily understand the difference between the input and the error message associated with it.',
    anchor: 'associate-input-error-messaging-with-the-input-it-corresponds-to',
    automated: 'partial',
    about: 'An error message next to a field is only heard if the field points at it. aria-describedby makes the message part of the field\'s announcement.',
    measures: 'Finds fields marked aria-invalid="true" or required with no aria-describedby and no aria-errormessage.',
    fix: 'Give the message an id and add aria-describedby="that-id" to the field; set aria-invalid="true" while the error stands.' },
  { id: 'states-not-color-only', section: 'forms', wcag: '1.4.1',
    title: 'Make sure that error, warning, and success states are not visually communicated by just color.',
    description: 'People who are color blind, who have other low vision conditions, or different cultural understandings for color may not see the state change, or understand what is being communicated.',
    anchor: 'make-sure-that-error-warning-and-success-states-are-not-visually-communicated-by-just-color',
    automated: 'partial',
    about: 'A red border means nothing to someone who cannot see red. Pair every color state with text or an icon.',
    measures: 'Finds fields marked aria-invalid or required whose only visible cue is a color change (no adjacent text, icon or asterisk). Submitted-state behavior still needs a person.',
    fix: 'Add a text message, an icon with alt, or a symbol next to every field state that is shown by color.' },

  // ------------------------------------------------------------------ Media
  { id: 'no-autoplay', section: 'media', wcag: '1.4.2',
    title: 'Make sure that media does not autoplay.',
    description: 'Unexpected video and audio can be distracting and disruptive, especially for certain kinds of cognitive disability such as ADHD. Certain kinds of autoplaying video and animation can be a trigger for vestibular and seizure disorders.',
    anchor: 'make-sure-that-media-does-not-autoplay',
    automated: 'yes',
    about: 'Sound that starts on its own talks over a screen reader. Motion that starts on its own can make people with vestibular disorders ill.',
    measures: 'Finds audio and video elements with autoplay, and checks whether they are muted and whether they offer controls.',
    fix: 'Remove autoplay. If a background video must play, mute it, keep it short, and give it a pause button.' },
  { id: 'media-controls-markup', section: 'media', wcag: '1.3.1',
    title: 'Ensure that media controls use appropriate markup.',
    description: 'Examples include making sure an audio mute button has a pressed toggle state when active, or that a volume slider uses <input type="range">.',
    anchor: 'ensure-that-media-controls-use-appropriate-markup',
    automated: 'partial',
    about: 'Custom players are usually divs with icons. A screen reader user needs each control to have a role, a name and a state: button, "Mute", pressed.',
    measures: 'Finds media elements without the controls attribute whose custom controls are not buttons with names, and toggle buttons without aria-pressed.',
    fix: 'Use the native controls attribute, or build controls from button elements with aria-label and aria-pressed, and input type="range" for sliders.' },
  { id: 'media-pausable', section: 'media', wcag: '2.1.1',
    title: 'Check to see that all media can be paused.',
    description: 'Provide a global pause function on any media element. If the device has a keyboard, ensure that pressing the Space key can pause playback. Be sure you also don\'t interfere with the Space key\'s default functionality if the media player does not have focus.',
    anchor: 'check-to-see-that-all-media-can-be-paused',
    automated: 'partial',
    about: 'Moving content that cannot be stopped keeps pulling attention away from everything else on the page. Every player needs a pause reachable by keyboard.',
    measures: 'Finds playing media elements with no controls attribute and no button nearby with pause/play in its name.',
    fix: 'Add controls, or a visible pause button that is a real button element.' },

  // ------------------------------------------------------------------ Video
  { id: 'captions', section: 'video', wcag: '1.2.2',
    title: 'Confirm the presence of captions.',
    description: 'Captions allow a person who cannot hear the audio content of a video to still understand its content.',
    anchor: 'confirm-the-presence-of-captions',
    automated: 'partial',
    about: 'Captions serve deaf and hard of hearing people, people in noisy or silent places, and people reading in a second language.',
    measures: 'Finds video elements with no track element of kind captions or subtitles. Embedded players (YouTube, Vimeo) are listed for a manual check.',
    fix: 'Add <track kind="captions" src="…" srclang="en" label="English"> to every video with speech. For embedded players, upload captions on the platform.' },
  { id: 'seizure-triggers', section: 'video', wcag: '2.3.1',
    title: 'Remove seizure triggers.',
    description: 'Certain kinds of strobing or flashing animations will trigger seizures.',
    anchor: 'remove-seizure-triggers',
    automated: 'no',
    about: 'Content that flashes more than three times a second can trigger a seizure in people with photosensitive epilepsy.',
    measures: 'Not automated for video content. CSS animations that cycle faster than three times a second are reported under Animation.',
    fix: 'Never flash more than three times in any one second. Check video with the Photosensitive Epilepsy Analysis Tool (PEAT).' },

  // ------------------------------------------------------------------ Audio
  { id: 'transcripts', section: 'audio', wcag: '1.1.1',
    title: 'Confirm that transcripts are available.',
    description: 'Transcripts allow people who cannot hear to still understand the audio content. It also allows people to digest audio content at a pace that is comfortable to them.',
    anchor: 'confirm-that-transcripts-are-available',
    automated: 'partial',
    about: 'A transcript is the text alternative for audio: searchable, skimmable, and readable by everyone.',
    measures: 'Finds audio elements with no link or details element nearby whose text mentions a transcript.',
    fix: 'Publish a full transcript next to every audio player, or link to one from beside the player.' },

  // ------------------------------------------------------------- Appearance
  { id: 'specialized-browsing-modes', section: 'appearance', wcag: '1.4.1',
    title: 'Check your content in specialized browsing modes.',
    description: 'Activate modes such as Windows High Contrast or Inverted Colors. Is your content still legible? Are your icons, borders, links, form fields, and other content still present? Can you tell where you are?',
    anchor: 'check-your-content-in-specialized-browsing-modes',
    automated: 'partial',
    about: 'In Windows High Contrast (forced colors) the browser replaces every color. Anything drawn only with a background color or background image vanishes: icon buttons, custom checkboxes, focus rings drawn with box-shadow.',
    measures: 'Emulates forced-colors and looks for controls that lose their visible boundary or icon (background-only icons with no text, no border and no SVG).',
    fix: 'Draw icons as inline SVG using currentColor, give controls a real border, and use outline for focus so forced colors can recolor it.' },
  { id: 'text-size-200', section: 'appearance', wcag: '1.4.4',
    title: 'Increase text size to 200%.',
    description: 'Is the content still readable? Does increasing the text size cause content to overlap?',
    anchor: 'increase-text-size-to-200percent',
    automated: 'yes',
    about: 'Many people with low vision zoom the browser to 200%. Text in fixed-height boxes gets cut off, and absolutely positioned elements begin to overlap.',
    measures: 'Zooms the page to 200% and finds text that is clipped or overlapping that was not at 100%.',
    fix: 'Avoid fixed heights on text containers. Size in rem and let boxes grow.' },
  { id: 'proximity', section: 'appearance', wcag: '1.3.3',
    title: 'Double-check that good proximity between content is maintained.',
    description: 'Use the straw test to ensure people who depend on screen zoom software can still easily discover all content.',
    anchor: 'double-check-that-good-proximity-between-content-is-maintained',
    automated: 'no',
    about: 'A screen magnifier shows a few centimetres of page at a time. A label on the far left and its value on the far right, or an error message far from its field, are never seen together.',
    measures: 'Not automated. Look at the page through a straw: does everything that belongs together sit together?',
    fix: 'Keep labels beside their fields, messages beside their cause, and totals beside the numbers they sum.' },
  { id: 'color-not-only-cue', section: 'appearance', wcag: '1.4.1',
    title: 'Make sure color isn\'t the only way information is conveyed.',
    description: 'Can you still see where links are among body content if everything is grayscale?',
    anchor: 'make-sure-color-isnt-the-only-way-information-is-conveyed',
    automated: 'partial',
    about: 'Charts with a color legend, required fields in red, links in blue: all invisible to someone who cannot tell those colors apart or who prints in black and white.',
    measures: 'Reports links distinguished by color alone (see Controls) and form states shown by color alone (see Forms). Other color-coded content needs a person.',
    fix: 'Pair every color with a second cue: text, an icon, a pattern, an underline.' },
  { id: 'instructions-not-sensory', section: 'appearance', wcag: '1.3.3',
    title: 'Make sure instructions are not visual or audio-only.',
    description: 'Use a combination of characteristics to write cues, especially the actual names of sections and elements, rather than just descriptions such as location ("on the right") or audio ("after the tone").',
    anchor: 'make-sure-instructions-are-not-visual-or-audio-only',
    automated: 'partial',
    about: '"Click the green button on the right" helps nobody who cannot see green or right. Name the button.',
    measures: 'Searches the visible text for instructions that rely on color, shape, position or sound alone.',
    fix: 'Refer to controls by their name: "press Save", not "press the button below".' },
  { id: 'simple-layout', section: 'appearance', wcag: '1.4.10',
    title: 'Use a simple, straightforward, and consistent layout.',
    description: 'A complicated layout can be confusing to understand and use.',
    anchor: 'use-a-simple-straightforward-and-consistent-layout',
    automated: 'partial',
    about: 'A layout that reflows into one column at narrow widths, without sideways scrolling, is what 1.4.10 asks for. It is also what people with cognitive disabilities and people using magnifiers need.',
    measures: 'Reflows the page to a 320px-wide viewport (400% zoom of 1280) and checks for two-dimensional scrolling. Consistency between pages needs a person.',
    fix: 'Let the layout collapse to one column below about 400px. Replace fixed widths with max-width.' },

  // -------------------------------------------------------------- Animation
  { id: 'subtle-animation', section: 'animation', wcag: '2.3.1',
    title: 'Ensure animations are subtle and do not flash too much.',
    description: 'Certain kinds of strobing or flashing animations will trigger seizures. Other animations may be distracting and disruptive, especially for certain kinds of cognitive disability such as ADHD.',
    anchor: 'ensure-animations-are-subtle-and-do-not-flash-too-much',
    automated: 'partial',
    about: 'Three flashes in a second is the seizure threshold. Well below that, constant looping motion still pulls attention away from reading.',
    measures: 'Lists running CSS animations that repeat indefinitely, and flags any that cycle faster than three times per second or cover a large area.',
    fix: 'Keep animation short, run it once, and never flash. Anything that loops needs a pause control.' },
  { id: 'pause-background-video', section: 'animation', wcag: '2.2.2',
    title: 'Provide a mechanism to pause background video.',
    description: 'Background video can be distracting, especially if content is placed over it.',
    anchor: 'provide-a-mechanism-to-pause-background-video',
    automated: 'yes',
    about: 'Moving content that starts automatically, lasts more than five seconds and sits beside other content must have a way to pause it.',
    measures: 'Finds autoplaying, looping video without controls and without a pause button near it.',
    fix: 'Add a visible pause button (a real button element) beside or over the video, or remove the autoplay.' },
  { id: 'prefers-reduced-motion', section: 'animation', wcag: '2.3.3',
    title: 'Make sure all animation obeys the prefers-reduced-motion media query.',
    description: 'Remove animations when the "reduce motion" setting is activated. If an animation is necessary to communicate meaning for a concept, slow its duration down.',
    anchor: 'make-sure-all-animation-obeys-the-prefers-reduced-motion-media-query',
    automated: 'yes',
    about: 'People with vestibular disorders switch on "reduce motion" in their operating system. Animation that ignores that setting can cause dizziness and nausea.',
    measures: 'Turns on prefers-reduced-motion in the browser and counts the CSS animations and transitions still running.',
    fix: 'Wrap animation in @media (prefers-reduced-motion: no-preference), or set animation: none and transition: none under (prefers-reduced-motion: reduce).' },

  // --------------------------------------------------------- Color contrast
  { id: 'contrast-normal-text', section: 'color-contrast', wcag: '1.4.3',
    title: 'Check the contrast for all normal-sized text.',
    description: 'Level AA compliance requires a contrast ratio of 4.5:1.',
    anchor: 'check-the-contrast-for-all-normal-sized-text',
    automated: 'yes',
    about: 'Text under 24px (or under 18.66px bold) must reach 4.5:1 against its background so that people with moderately low vision, and everyone on a dim screen in daylight, can read it.',
    measures: 'Computes the contrast between each run of normal-sized text and the first solid background behind it.',
    fix: 'Darken the text or lighten the surface until the pair reaches 4.5:1. Change the design token so every use moves with it.' },
  { id: 'contrast-large-text', section: 'color-contrast', wcag: '1.4.3',
    title: 'Check the contrast for all large-sized text.',
    description: 'Level AA compliance requires a contrast ratio of 3:1.',
    anchor: 'check-the-contrast-for-all-large-sized-text',
    automated: 'yes',
    about: 'Large text (24px and above, or 18.66px bold) is easier to read, so 3:1 is enough.',
    measures: 'Computes the contrast between each run of large text and the first solid background behind it.',
    fix: 'Adjust the color pair until it reaches 3:1.' },
  { id: 'contrast-icons', section: 'color-contrast', wcag: '1.4.11',
    title: 'Check the contrast for all icons.',
    description: 'Level AA compliance requires a contrast ratio of 3.0:1.',
    anchor: 'check-the-contrast-for-all-icons',
    automated: 'yes',
    about: 'An icon that stands in for a label has to be seen as clearly as the label would be. 1.4.11 asks for 3:1 for the parts of a graphic needed to understand it.',
    measures: 'Finds SVG icons inside controls with no text and measures their fill or stroke color against the background behind them.',
    fix: 'Recolor the icon to reach 3:1 against its background, or add a visible text label.' },
  { id: 'contrast-input-borders', section: 'color-contrast', wcag: '1.4.11',
    title: 'Check the contrast of borders for input elements (text input, radio buttons, checkboxes, etc.).',
    description: 'Level AA compliance requires a contrast ratio of 3.0:1.',
    anchor: 'check-the-contrast-of-borders-for-input-elements-text-input-radio-buttons-checkboxes-etc',
    automated: 'yes',
    about: 'If the edge of a text field cannot be seen, the person does not know where to click or type. A pale gray border on white is the usual failure.',
    measures: 'Measures each form field\'s border color against the surface around it, unless the field is distinguished by a filled background instead.',
    fix: 'Darken the border to reach 3:1 against the page background (#767676 on white is the lightest gray that passes).' },
  { id: 'contrast-over-media', section: 'color-contrast', wcag: '1.4.3',
    title: 'Check text that overlaps images or video.',
    description: 'Is text still legible?',
    anchor: 'check-text-that-overlaps-images-or-video',
    automated: 'yes',
    about: 'A photograph has light and dark areas; white text over it is legible on the dark parts and disappears on the light ones. The requirement applies to the worst spot.',
    measures: 'Makes the text transparent, screenshots the region, and samples the real pixels behind it. The ratio reported is against the worst-case backdrop color found.',
    fix: 'Add a dark or light scrim behind the text, move the text off the picture, or pin the gradient to a fixed end color.' },
  { id: 'selection-colors', section: 'color-contrast', wcag: '1.4.3',
    title: 'Check custom ::selection colors.',
    description: 'Are your custom ::selection colors sufficiently contrasting? Improper contrast in custom CSS declarations could make highlighted text unreadable.',
    anchor: 'check-custom-selection-colors',
    automated: 'yes',
    about: 'People select text to read it more easily. A custom selection color that is close to the text color makes the selected text vanish.',
    measures: 'Reads ::selection rules from the stylesheets and computes the contrast of their text color against their background color.',
    fix: 'Choose a selection background that keeps 4.5:1 against the selected text color, or leave the browser default.' },

  // ------------------------------------------------------- Mobile and touch
  { id: 'orientation', section: 'mobile-and-touch', wcag: '1.3.4',
    title: 'Check that the site can be rotated to any orientation.',
    description: 'Does the site only allow portrait orientation?',
    anchor: 'check-that-the-site-can-be-rotated-to-any-orientation',
    automated: 'partial',
    about: 'People with a phone mounted on a wheelchair cannot rotate it. Content must work in both portrait and landscape.',
    measures: 'Looks for orientation-lock hints (screen.orientation.lock in scripts, orientation media queries that hide the main content). A rotation test still needs a device.',
    fix: 'Do not lock orientation. Test both orientations on a phone.' },
  { id: 'no-horizontal-scroll', section: 'mobile-and-touch', wcag: '1.4.10',
    title: 'Remove horizontal scrolling.',
    description: 'Requiring someone to scroll horizontally can be difficult for some, irritating for all.',
    anchor: 'remove-horizontal-scrolling',
    automated: 'yes',
    about: 'Sideways scrolling means reading every line in two moves. It is caused by an element wider than the screen: a fixed-width table, an image, a long unbroken string.',
    measures: 'Checks whether the document is wider than the viewport at the scanned width and lists the elements that overflow.',
    fix: 'Constrain the overflowing element with max-width: 100%, allow wrapping, and let tables scroll inside their own container.' },
  { id: 'target-size', section: 'mobile-and-touch', wcag: '2.5.5',
    title: 'Ensure that button and link icons can be activated with ease.',
    description: 'Make sure things like hamburger menus, social media icons, gallery viewers, and touch controls can be activated with ease by people who have different sized hands and a range of stylus sizes.',
    anchor: 'ensure-that-button-and-link-icons-can-be-activated-with-ease',
    automated: 'yes',
    about: 'A fingertip covers about 44 CSS pixels. WCAG 2.5.8 (AA) requires 24x24 unless there is spacing around the target; 2.5.5 (AAA) asks for 44x44.',
    measures: 'Measures every control. Controls under 24x24 that are also crowded by neighbors fail; controls under 44x44 are noted for AAA.',
    fix: 'Grow the target or its padding to at least 24x24, ideally 44x44, including for icon-only controls.' },
  { id: 'scroll-space', section: 'mobile-and-touch', wcag: '2.4.1',
    title: 'Ensure sufficient space between interactive items in order to provide a scroll area.',
    description: 'People with motor control issues such as hand tremors may have a very difficult time scrolling past interactive items which feature zero spacing.',
    anchor: 'ensure-sufficient-space-between-interactive-items-in-order-to-provide-a-scroll-area',
    automated: 'yes',
    about: 'A screen packed edge to edge with controls leaves nowhere safe to put a thumb down to scroll. Each accidental touch fires something.',
    measures: 'Finds controls that touch or nearly touch a neighbor (under 8px apart) at phone widths.',
    fix: 'Add margin between adjacent controls and leave some inert space on every screen.' }
];

const BY_ID = Object.fromEntries(ITEMS.map(i => [i.id, i]));

function wcagFor(code) {
  const w = WCAG[code];
  if (!w) return { code, name: '', level: '', url: '' };
  return { code, name: w.name, level: w.level, note: w.note || null,
           url: w.url || (WCAG_BASE + w.slug + '.html') };
}

function itemFor(id) {
  const it = BY_ID[id];
  if (!it) return null;
  return { ...it, criterion: wcagFor(it.wcag), checklistUrl: CHECKLIST_BASE + '#' + it.anchor,
           sectionTitle: SECTIONS.find(s => s.id === it.section).title };
}

module.exports = { WCAG, SECTIONS, ITEMS, BY_ID, wcagFor, itemFor, WCAG_BASE, CHECKLIST_BASE };
